apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-cpu
  template:
    metadata:
      labels:
        app: fastapi-cpu
    spec:
      containers:
        - name: fastapi
          image: fastapi-cpu:latest
          imagePullPolicy: IfNotPresent       
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
